version: '2'
services:
  zb_jenkins:
    image: hub.c.163.com/library/jenkins:latest
    volumes:
      - ./data/jenkins:/var/jenkins_home
      # - /bin/docker:/usr/bin/docker
      # - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "8897:8080"