version: '2'
services:
  zb_jenkins:
    image: hub.c.163.com/public/jenkins:2.60.2
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - ~/.ssh:/root/.ssh
      - /home/zbaotool/Android:/root/data/Android
      # - /bin/docker:/usr/bin/docker
      # - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "8897:8080"
    env_file: variables.env
    environment:
      - RACK_ENV=development
      - GRADLE_HOME=/root/data/Android/gradle-4.7
      - JAVA_HOME=/root/data/Android/jdk1.8.0_161
      - ANDROID_HOME=/root/data/Android/Sdk
      # - PATH=${GRADLE_HOME}/bin:$PATH
      # - PATH=${JAVA_HOME}/bin:$PATH
      # - PATH=${ANDROID_HOME}/tools:$PATH
      # - PATH=${ANDROID_HOME}/platform-tools:$PATH
