version: '2'
services:
  zb_jenkins:
    image: hub.c.163.com/public/jenkins:2.60.2
    container_name: zb_jenkins
    volumes:
      - ./data/jenkins:/var/jenkins_home
      - ~/.ssh:/root/.ssh
      - /home/zbaotool/Android:/root/data/Android
      # - /bin/docker:/usr/bin/docker
      # - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - "8897:8080"
    # env_file: ./variables.env
    environment:
    - GRADLE_HOME=/root/data/Android/gradle-4.7
    - JAVA_HOME=/root/data/Android/jdk1.8.0_161
    - ANDROID_HOME=/root/data/Android/Sdk
      # PATH: ${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/tools:${JAVA_HOME}/bin:${GRADLE_HOME}/bin:${PATH}
